/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CustomOrdersRouteImport } from './routes/custom-orders'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ReturnPolicyRouteImport } from './routes/return-policy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomOrdersRoute = CustomOrdersRouteImport.update({
  id: '/custom-orders',
  path: '/custom-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnPolicyRoute = ReturnPolicyRouteImport.update({
  id: '/return-policy',
  path: '/return-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/custom-orders': typeof CustomOrdersRoute
  '/faq': typeof FaqRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/search': typeof SearchRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/custom-orders': typeof CustomOrdersRoute
  '/faq': typeof FaqRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/search': typeof SearchRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/custom-orders': typeof CustomOrdersRoute
  '/faq': typeof FaqRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/search': typeof SearchRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/categories'
    | '/contact'
    | '/custom-orders'
    | '/faq'
    | '/privacy-policy'
    | '/return-policy'
    | '/search'
    | '/shipping-policy'
    | '/shop'
    | '/terms'
    | '/wishlist'
    | '/category/$slug'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/categories'
    | '/contact'
    | '/custom-orders'
    | '/faq'
    | '/privacy-policy'
    | '/return-policy'
    | '/search'
    | '/shipping-policy'
    | '/shop'
    | '/terms'
    | '/wishlist'
    | '/category/$slug'
    | '/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/categories'
    | '/contact'
    | '/custom-orders'
    | '/faq'
    | '/privacy-policy'
    | '/return-policy'
    | '/search'
    | '/shipping-policy'
    | '/shop'
    | '/terms'
    | '/wishlist'
    | '/category/$slug'
    | '/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  ContactRoute: typeof ContactRoute
  CustomOrdersRoute: typeof CustomOrdersRoute
  FaqRoute: typeof FaqRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ReturnPolicyRoute: typeof ReturnPolicyRoute
  SearchRoute: typeof SearchRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  ShopRoute: typeof ShopRoute
  TermsRoute: typeof TermsRoute
  WishlistRoute: typeof WishlistRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-orders': {
      id: '/custom-orders'
      path: '/custom-orders'
      fullPath: '/custom-orders'
      preLoaderRoute: typeof CustomOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/return-policy': {
      id: '/return-policy'
      path: '/return-policy'
      fullPath: '/return-policy'
      preLoaderRoute: typeof ReturnPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  ContactRoute: ContactRoute,
  CustomOrdersRoute: CustomOrdersRoute,
  FaqRoute: FaqRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ReturnPolicyRoute: ReturnPolicyRoute,
  SearchRoute: SearchRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  ShopRoute: ShopRoute,
  TermsRoute: TermsRoute,
  WishlistRoute: WishlistRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
